---
name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
      - enhancement
      - feature
  patch:
    labels:
      - patch
      - bug
      - bugfix
      - fix
      - dependencies
  default: patch
template: |
  ## What's Changed

  $CHANGES
