#!/bin/sh
# s6 calls finish with $1=exit_code (256 = killed by s6 itself, i.e. normal stop)
# Only bring down the container on an unexpected crash
[ $# -gt 0 ] || exit 0
[ "${1}" -ne 256 ] || exit 0
exec s6-svscanctl -t /var/run/s6/services
