---
name: Deploy Edge

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  workflows:
    # yamllint disable-line rule:line-length
    uses: hassio-addons/workflows/.github/workflows/addon-deploy.yaml@383c10d83acbe341acbb35a4a61bfd14827f00f0
    with:
      repository_edge: "hassio-addons-edge"
    secrets:
      DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
