---
name: Deploy

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published

permissions:
  contents: read
  packages: write

jobs:
  workflows:
    # yamllint disable-line rule:line-length
    uses: hassio-addons/workflows/.github/workflows/addon-deploy.yaml@383c10d83acbe341acbb35a4a61bfd14827f00f0
    with:
      slug: "hassio-addon-vault"
      repository: "hassio-addons"
      repository_beta: "hassio-addons-beta"
    secrets:
      DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
